# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar ***.jar --spring.profiles.active=test
#   生产环境：java -jar ***.jar --spring.profiles.active=prod
spring:
  profiles:
    active: @env@
    include: common

  output:
    ansi:
      enabled: ALWAYS


# 离职员工积分处理任务 每天早上7点执行( 0 0 7 * * ?) 测试每一分钟
leaveEmployee:
  jobs:
    cron: 0 0/3 *  * * ?
#    cron: 0 0 7 * * ?

#节日礼金邮件通知任务 每天早上7点执行
campaign:
  jobs:
#    cron: 0 0 7 * * ?
    cron: 0 0/3 *  * * ?

#每天零点检查过期卡密(0 0 0 * * ? )
cardKey:
  cron: 0 0 0 * * ?

#---
# 开发环境配置
#spring:
#  profiles: dev

#---
# 测试环境配置
#spring:
#  profiles: test

#---
# 生产环境配置
#spring:
#  profiles: prod

file:
  brand:
    url: http://basedata.qn.seagoor.com
