###会员服务启动端口号
server:
  port: 8050
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-wangmeng-order
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

