#指定log的配置文件
logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:/mapper/**/**/*Mapper.xml
  type-aliases-package: com.lx.benefits.bean.entity

wx:
  jsCode2SessionUrl: https://api.weixin.qq.com/sns/jscode2session
  wxaCodeUrl: https://api.weixin.qq.com/wxa/getwxacodeunlimit
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
  indexPage: pages/company/index
  defaultAvatar: https://*.png

spring:
  servlet:
    multipart:
       max-file-size: 5MB
