spring:
  jackson:
    #JsonInclude.Include.ALWAYS              默认
    #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #数据源
  datasource:
    url: jdbc:mysql://106.15.102.253:3306/fuliserver?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&tinyInt1isBit=false&useSSL=false
    username: xigoudev
    password: 1qaz@WSX
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query-timeout: 900000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow: 127.0.0.1
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny: 192.168.1.118
        enabled: true
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        enabled: true
  #redis
  redis:
    jedis:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-idle: 100 # 连接池中的最大空闲连接  默认 8
        min-idle: 10 # 连接池中的最小空闲连接 默认 0
        max-wait: 6000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
    timeout: 6000ms # 连接超时时间（毫秒）
    host: 106.15.102.253
    port: 6379
    password: xigou!@#

  session:
    store-type: none


wx:
  appId: wx8d51c0c883fd3c9a
  appSecret: 7010fca094f7441176a636655ee44357

pay:
  alipay:
    appId: 2019022863399539
    sellerPayId: 1  # pay_account表对应支付账号ID
    partner: 2088431562188037
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgyeyQnI3YSLIL6OaFd7mbpb2YinHYou/46KG07Ip69MR1q574cZKa4N9lZTmmKGS9GcXM51m1gjG3MTNFZEWMr+nl5rwohAXphXipnV6U/Nr0RWZUcPvggRITWvvZWqCFmBSiErT4x+VAr3qowLW95mjRkip7k9YxfAwkMs9+NnKmBX2pv7C+OyecINP0yC2aci4KPlKbtbKaEhVzYHlp/NLp25DZrPPnjg4shoQ8tZ/3WK5UpA5yKZjItVDKmqH/OO+EDS4Ewkl7cHPEq35WwladLcS/HB/6vOKPo3lk5WfgVIvMln7afJamtvtV30go+RiN+b9ftLQkSmydn2ndAgMBAAECggEABfd4T+V/XgdUlByQcWN//8amwoJgtylUvmfjmFMu0GFE6Rj1TULprdWqdJjNCt1034+VR4VOTu4F6kZpIKoX6qCcjWuCj/5WOdQ6JhEw8VZwyZ/JrFiFAE/J2+4EaoxyaIK8QUdwb8r7NutMIfcEx4dFXIGQEgXqbOuth6pbCNPtABaLvSA/JscKKZ8xf7tRmx28trMOd9X02uregoKIeQfdswY/lD2hNlgYj5BsFUFmvjwOjvs/GxgCWuHjGNwefQAL9Xyy72+vRAOp+HaWQHUdeC6LC7PzU/amOhPG1CSPomDm0x2WCn2I1A0LGGkxrcFS3811B5CVqGt+qojqAQKBgQD9Ax1EwfZFeQBUtJQQZzBGd0DbxblLV7PU07r0nzm8GQp0dD/x+oF0DfaBQf3G98zx1wB82CyQ+BGaKVWOdZCai/WtZ1FmDtyfzzJa2FghCO9Fz4sjBOTOcLp8RwMZ2MAV1tXaLokpJxQIYJ0GhuS1ByPeVmhhABJ0raZGKYfO2wKBgQCisAHsurxWUg1ATvxvdKpJ1BqaOMEdsrMOhl6OlAqi1fa2k4IVWLoVU48+otoKJSx4RRo3D6UqSICvKQhkkcDVpfF5G9J5NZ8QBTKFHssUJDT30xuOH1/XcWFTrk9vjlC2W/b8++dRe3P+8vT+VvLGnHbYag8tALoeg/5aB4E7pwKBgQDdb7JYESIHH6XIfNrxmD5KDek3788CP9nmNQD1Q732ADyEO5ITqFlQR0AtVKJVV1+JcdC9cz1eC57sO6zjp8VNXZ1BjKFTH0K8o0zA8YQANZ+ki8aMeaX/f+3XAxeVsXw8IPC9qejlmYwQ4O3NXpYgUgV0fE+SRcvhTnGuCn8P7QKBgAvvbbS4XmjWzDITmWFz5apU7T6zOze6jHhcU0OSiNU5bUgnujtmrwAxiSjHOcfUwlZwe2PeufdIKmivUfZO2x7Rdc20xNQvouPB/drWT3/CyEAGNNdQZe+gWcuR1jIQ9srqJEybDnVj4TarDF48csMvZ2ipH0Pl8cGbXWWtd0WxAoGAOq4Jzou4WX40+lDUhfWuIChrJateLlPV4lK0jfxeG6zwJFIhOhwS2h5YMtBgUkb6bhGjFxsux+SNEJcG4fWc5uSn+HNy+6oLH9THMrVbJ+PT33tz3qVzR2rWvAE0tveRi/+k3UNtAeavfWmhTKW1jLoI4vFqO+QoVrqMXdiyzuw=
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoMnskJyN2EiyC+jmhXe5m6W9mIpx2KLv+OihtOyKevTEdaue+HGSmuDfZWU5pihkvRnFzOdZtYIxtzEzRWRFjK/p5ea8KIQF6YV4qZ1elPza9EVmVHD74IESE1r72VqghZgUohK0+MflQK96qMC1veZo0ZIqe5PWMXwMJDLPfjZypgV9qb+wvjsnnCDT9MgtmnIuCj5Sm7WymhIVc2B5afzS6duQ2azz544OLIaEPLWf91iuVKQOcimYyLVQypqh/zjvhA0uBMJJe3BzxKt+VsJWnS3Evxwf+rzij6N5ZOVn4FSLzJZ+2nyWprb7Vd9IKPkYjfm/X7S0JEpsnZ9p3QIDAQAB
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApXf+68t237GuJ8ZbqCsnUjhZ9DrsoorhlYOvxh29PPrqjdXDGPXQwPxTc90xyzdZlCMHDK37v34wG/ilq497vtXJ0g3nwzwhkT4/VmJptwxLVd3Ez3ZpoDszMowML8r8Gg7B8Zgu7DSDtAOvgwMc47mwYrBa69RlREPFtScAakGForiRMC1RYZjmFCsgiQYYjyAm6J8ZEJKj9j12CKPv/4otWpNr3tCrh5crJg1l+2iVlWHQ5NQ6mLYBPbFk52uaKvdlqJ2Xq/nEcB2m+BR2lQTgFBjLW3XmF/KrbqNXpHEz2O7BepQntSvGrPeQqnijFEHpREKAgiGggZu7EbbDNwIDAQAB
    notifyUrl: https://dnser.lixiangshop.com/pay/alipayCallback
    returnUrl: http://aon.lixiangshop.com/my/orders
    logPath: /logs
    inputCharset: GBK
    signType: RSA2
  wxPay:
    sellerPayId: 2  # pay_account表对应支付账号ID
    appId: wx8d51c0c883fd3c9a
    mchId: 1453824202
    mchKey: thisisxigouguojimiyao12333333333
    notifyUrl: https://dnser.lixiangshop.com/pay/wxPayCallback
    keyPath: /opt/cert/wechat/apiclient_cert.p12


qiniu:
  access:
    key: r_CJpAAHWFa1vE0hi-ap9PpxCDfNefJnODso0WJC
  bucket: supplier
  path: http://supplier.qn.seagoor.com/
  secret:
    key: 0a_gpdprqDGFUEU4xYgvNmJO_ipRdqgG_iJcQ7s8


third:
  platform:
    seller:
      jd:
        id: 1
        name: 京东
      yx:
        id: 3
        name: 网易严选
        
yx:
  apiHost: http://openapi-test.you.163.com
  apiUrl: /channel/api.json
  apiKey: 9c868d2145714773bc7bb22d0b2c48fb
  apiSecret: b00016ec7f044154baaac1cfedfdc211

yian:
  apiHost: https://uatbizapi.yianyouxuan.com
  clientId: iGJcuOa5cyps1UT7RQqKnDkYwNO9sG0t6vfaeBUg
  clientSecret: JMvQx9PrK900712aA1AhGFpzB3nDRBKBnbJVjvOF9LhwoWxislSDj2PnXArx0t4YkpY8e11tWkFTW7Mt5wxvc9OasxyhMVDanupcvLK8Y4vBsJ3NG3Z7NmKPYoOf9G9g

yibao:
  apiUrl: https://openapi-test.smartebao.com:20082/gateway/receive
  appId: FULI0001
  appKey: abcdefghij1234567890abcdefghij1234567890
  platformId: APP_FULI
  orgCode: smartebao
  enterprId: 200
  