# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar ***.jar --spring.profiles.active=test
#   生产环境：java -jar ***.jar --spring.profiles.active=prod
spring:
  profiles:
    active: @env@
    include: common

  output:
    ansi:
      enabled: ALWAYS

#---
# 开发环境配置
#spring:
#  profiles: dev

#---
# 测试环境配置
#spring:
#  profiles: test

#---
# 生产环境配置
#spring:
#  profiles: prod