server:
    port: 8183 #端口号
    tomcat:
      remote-ip-header : x-forwarded-for
      protocol-header : x-forwarded-proto
    compression:
      min-response-size: 512 #压缩文件最小大小(kb)
      enabled: true #是否压缩
      mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg #要压缩的文件格式
    undertow:
      io-threads: 4 #io线程数
      worker-threads: 10 #工作线程数
      buffer-size: 16384 #每个缓冲的字节数
      accesslog:
        enabled: true #是否开启undertow日志
        dir: /logs/benefits-mall/server_log #undertow日志目录
        pattern: combined #日志格式


spring:
  profiles:
    include: common-dev
  application:
      name: benefits-mall
  http:
      encoding.charset: UTF-8
      encoding.force: false


#  data:
#    elasticsearch:
#      cluster-name: *
#      cluster-nodes: *
#    redis:
#      repositories:
#        enabled: false

