server:
  port: 8000
spring:
  application:
    name: app-wangmeng-member
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8100/eureka
###集群地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka,http://localhost:9100/eureka
    register-with-eureka: true
    fetch-registry: true
swagger:
  base-package: com.wangmeng.api.controller